### ISSUE TITLE
Memory Issue?

### ISSUE THREAD

**Issue by patrickvdv** [10gic/vanitygen-plusplus#34] opened 2022-06-13 14:26 UTC
Hi,

Just compiled vanitygen-plusplus on Ubuntu 22.04 LTS (GNU/Linux 5.15.0-25-generic x86_64) OpenSSL 3.0.2 15 Mar 2022 (Library: OpenSSL 3.0.2 15 Mar 2022)

make and make all both compiled without any errors.

vanitygen is working:
@vanity:~/vanitygen-plusplus$ ./vanitygen++ -F p2tr bc1ptest
Pattern: bc1ptest
BTC Address: bc1ptestscwxw6d2qxsf5f07vjsn5n7eqe6m0pxxlaafwjlwggs890ss6ajy0x
BTC Privkey (hex): ba74710c1e62172aa618f135aef713b28869178875835d7de28696b7c0671dd7

But if I try for example 7 characters the process stops with a "Killed" message.
@vanity:~/vanitygen-plusplus$ ./vanitygen++ -F p2tr bc1test123
Pattern: bc1test123
[4.53 Kkey/s][total 8832840]          Killed

On the console (of my VM) I see the message: Out of memory: Killed process xxx (vanitygen++) total-vm:16228844Kb
I've raised the assigned memory from 12gb where is stops after approximate [total 6568229] attempts 
with 16Gb if stops after [total 8832840] attempts.
On the VM I see the memory usage rise evenly till it hits 100%

Also did some testing with (native witness) /vanitygen++ -F p2wpkh but have the same issue.
@vanity:~/vanitygen-plusplus$ ./vanitygen++ -F p2wpkh bc1qtest123
Pattern: bc1qtest123
[6.53 Kkey/s][total 8838793]      Killed

Any help is appreciated.

**Comment by MrGoro** [comment] 2022-07-10 14:45
Can confirm the problem. Also used Ubuntu 22.04. Process gets killed after about 15 minutes with 32GB of memory.

**Comment by 10gic** [comment] 2022-07-10 16:40
@patrickvdv  @MrGoro Thanks for reporting the issue. I don't have an Ubuntu 22.04 server, please help me to see if this issue is resolved.

**Comment by MrGoro** [comment] 2022-07-10 16:43
Is there any option to provide detailed logs? That problem can be reproduced easily.

**Comment by 10gic** [comment] 2022-07-11 01:58
@MrGoro Sorry, I forgot to mention that this issue has been resolved in commit  303df78232765713bbb459ffb0d50a930e4a7304, I just wanted you to check if this issue has been resolved.

**Comment by MrGoro** [comment] 2022-07-11 05:11
Ok now I got it. Just testet the updated version and can confirm that I do not have any issues. Seems to be resolved for me.

**Closed** 2022-07-11 05:32 UTC

**Comment by patrickvdv** [comment] 2022-07-11 10:18
Same here, issue is solved with the latest version. Thanks!
